# Generated by Django 3.2.16 on 2024-05-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Admin Email'),
        ),
    ]
