# Generated by Django 3.2.16 on 2024-05-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_nation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icons_data',
            field=models.JSONField(default=list, verbose_name='Icons Data'),
        ),
    ]
