# Generated by Django 3.2.16 on 2024-07-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_icons_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_creta',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_two_factor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='token_creta',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
