# Generated by Django 3.2.16 on 2024-07-02 07:39

from django.db import migrations


def copy_id_to_id_creta(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        user.id_creta = str(user.id)
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_auto_20240705_1907'),
    ]

    operations = [
        migrations.RunPython(copy_id_to_id_creta),
    ]
