# Generated by Django 3.2.16 on 2024-07-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin_email',
        ),
        migrations.AddField(
            model_name='user',
            name='token_creta_expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token Expired At (Creta)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_creta',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID (Creta)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_two_factor',
            field=models.BooleanField(default=False, verbose_name='Is Two Factor (Creta)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_creta',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Token (Creta)'),
        ),
    ]
