# Generated by Django 3.2.16 on 2023-11-08 12:33

import community.bases.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Deleted')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='Deleted')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('comment_count', models.IntegerField(default=0, verbose_name='Comment Count')),
                ('point', models.IntegerField(default=0, verbose_name='Point')),
                ('community_visit_point', models.IntegerField(default=0, verbose_name='Community Visit Point')),
                ('post_point', models.IntegerField(default=0, verbose_name='Post Point')),
                ('posts_like_point', models.IntegerField(default=0, verbose_name='Posts Like Point')),
                ('posts_dislike_point', models.IntegerField(default=0, verbose_name='Posts Dislike Point')),
                ('comment_point', models.IntegerField(default=0, verbose_name='Comment Point')),
                ('comments_like_point', models.IntegerField(default=0, verbose_name='Comments Like Point')),
                ('comments_dislike_point', models.IntegerField(default=0, verbose_name='Comments Dislike Point')),
                ('post_count', models.IntegerField(default=0, verbose_name='Post Count')),
                ('reported_count', models.IntegerField(default=0, verbose_name='Reported Count')),
                ('community_visit_count', models.IntegerField(default=0, verbose_name='Club Visit Count')),
                ('posts_like_count', models.IntegerField(default=0, verbose_name='Posts Like Count')),
                ('posts_dislike_count', models.IntegerField(default=0, verbose_name='Posts Dislike Count')),
                ('comments_like_count', models.IntegerField(default=0, verbose_name='Comment Like Count')),
                ('comments_dislike_count', models.IntegerField(default=0, verbose_name='Comment DisLike Count')),
                ('user_data', models.JSONField(blank=True, null=True, verbose_name='User Data')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('level', models.IntegerField(default=1, verbose_name='Level')),
                ('last_visit', models.DateTimeField(blank=True, null=True, verbose_name='Last Visit')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='communities.community', verbose_name='Community')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
                'ordering': ['-created'],
            },
            bases=(community.bases.models.UpdateMixin, models.Model),
        ),
    ]
