# Generated by Django 3.2.16 on 2024-12-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comments_emoji_count',
            field=models.IntegerField(default=0, verbose_name='Comments Emoji Count'),
        ),
        migrations.AddField(
            model_name='profile',
            name='comments_emoji_point',
            field=models.IntegerField(default=0, verbose_name='Comments Emoji Point'),
        ),
        migrations.AddField(
            model_name='profile',
            name='posts_emoji_count',
            field=models.IntegerField(default=0, verbose_name='Posts Emoji Count'),
        ),
        migrations.AddField(
            model_name='profile',
            name='posts_emoji_point',
            field=models.IntegerField(default=0, verbose_name='Posts Emoji Point'),
        ),
    ]
