# Generated by Django 3.2.16 on 2023-11-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
    ]
