# Generated by Django 3.2.16 on 2023-11-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_insert_default_community_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['created'], 'verbose_name': 'Community', 'verbose_name_plural': 'Community'},
        ),
    ]
