# Generated by Django 3.2.16 on 2023-12-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_community_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='posts_data',
            field=models.JSONField(default=list, verbose_name='Editor Pick Posts Data'),
        ),
    ]
