# Generated by Django 3.2.16 on 2023-12-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_community_posts_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='banner_medias_data',
            field=models.JSONField(default=list, verbose_name='Banner Medias Data'),
        ),
    ]
