# Generated by Django 3.2.16 on 2024-02-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_community_banner_medias_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='title_ar',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='community',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='community',
            name='title_es',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='community',
            name='title_ja',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='community',
            name='title_ko',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='community',
            name='title_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='community',
            name='title_zh_hans',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='community',
            name='title_zh_hant',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
    ]
