# Generated by Django 3.2.16 on 2024-04-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_delete_community_no_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='logo_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Logo Image URL'),
        ),
    ]
