# Generated by Django 3.2.16 on 2024-07-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_auto_20240218_0501'),
        ('communities', '0018_update_logo_image_url'),
    ]

    operations = [
    ]
