# Generated by Django 3.2.16 on 2023-11-08 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_post_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
        ('profiles', '0002_initial'),
        ('communities', '0002_community_user'),
        ('comments', '0005_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportgroup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_groups', to=settings.AUTH_USER_MODEL, verbose_name='Reported User'),
        ),
        migrations.AddField(
            model_name='reportchoice',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_choices', to='communities.community', verbose_name='Community'),
        ),
        migrations.AddField(
            model_name='reportchoice',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_choices', to='profiles.profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='reportchoice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_choices', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='comments.comment', verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='report',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='posts.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='report',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='profiles.profile', verbose_name='Report User Profile'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.reportgroup', verbose_name='Report Group'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Report User'),
        ),
    ]
