from community.apps.posts.models.mixins.badge import PostBadgeModelMixin
from community.apps.posts.models.mixins.bookmark import PostBookmarkModelMixin
from community.apps.posts.models.mixins.community import PostCommunityModelMixin
from community.apps.posts.models.mixins.comment import PostCommentModelMixin
from community.apps.posts.models.mixins.image import PostMediaModelMixin
from community.apps.posts.models.mixins.like import PostLikeModelMixin
from community.apps.posts.models.mixins.point import PostPointModelMixin
from community.apps.posts.models.mixins.rank import PostRankModelMixin
from community.apps.posts.models.mixins.report import PostReportModelMixin
from community.apps.posts.models.mixins.share import PostShareModelMixin
from community.apps.posts.models.mixins.tag import PostTagModelMixin
from community.apps.posts.models.mixins.visit import PostVisitModelMixin
