POINT_PER_COMMUNITY_LEVEL = 0.3
POINT_PER_PROFILE_LEVEL = 0.4
POINT_PER_BOOKMARK = 10
POINT_PER_POST = 5
POINT_PER_COMMENT = 2
POINT_PER_POST_LIKE = 1
POINT_PER_POST_DISLIKE = 1
POINT_PER_COMMENT_LIKE = 1
POINT_PER_COMMENT_DISLIKE = 1
POINT_PER_POST_VISIT = 1
POINT_PER_COMMUNITY_VISIT = 1
POINT_PER_PARENT_COMMENT = 5

# FRIEND_POINT
FRIEND_POINT_PER_POST_LIKE = 1
FRIEND_POINT_PER_POST_UNLIKE = -1
FRIEND_POINT_PER_COMMENT_LIKE = 1
FRIEND_POINT_PER_COMMENT_UNLIKE = -1
FRIEND_POINT_PER_CHILD_COMMENT_LIKE = 1
FRIEND_POINT_PER_CHILD_COMMENT_UNLIKE = -1
FRIEND_POINT_PER_CREATE_COMMENT = 2
FRIEND_POINT_PER_DELETE_COMMENT = -2
FRIEND_POINT_PER_CREATE_CHILD_COMMENT = 2
FRIEND_POINT_PER_DELETE_CHILD_COMMENT = -2
FRIEND_POINT_PER_POST_MENTION = 1
FRIEND_POINT_PER_COMMENT_MENTION = 1
FRIEND_POINT_PER_CHILD_COMMENT_MENTION = 1
