# Generated by Django 3.2.16 on 2023-11-08 12:33

import community.apps.comments.models.mixins.image
import community.bases.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Deleted')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='Deleted')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=community.apps.comments.models.mixins.image.image_path, verbose_name='Image')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('total_like_count', models.IntegerField(default=0, verbose_name='Total Like Count')),
                ('like_count', models.IntegerField(default=0, verbose_name='Like Count')),
                ('fun_count', models.IntegerField(default=0, verbose_name='Fun Count')),
                ('healing_count', models.IntegerField(default=0, verbose_name='Healing Count')),
                ('legend_count', models.IntegerField(default=0, verbose_name='Legend Count')),
                ('useful_count', models.IntegerField(default=0, verbose_name='Useful Count')),
                ('empathy_count', models.IntegerField(default=0, verbose_name='Empathy Count')),
                ('devil_count', models.IntegerField(default=0, verbose_name='Devil Count')),
                ('dislike_count', models.IntegerField(default=0, verbose_name='Dislike Count')),
                ('point', models.IntegerField(default=0, verbose_name='Point')),
                ('reported_count', models.IntegerField(default=0, verbose_name='Reported Count')),
                ('user_data', models.JSONField(blank=True, null=True, verbose_name='User Data')),
                ('profile_data', models.JSONField(blank=True, null=True, verbose_name='Profile Data')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('content_summary', models.TextField(blank=True, null=True, verbose_name='Content Summary')),
                ('is_secret', models.BooleanField(default=False, verbose_name='Is Secret')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comment',
                'ordering': ['created'],
            },
            bases=(community.bases.models.UpdateMixin, models.Model),
        ),
    ]
