# Generated by Django 3.2.16 on 2024-12-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='emoji_count',
            field=models.IntegerField(default=0, verbose_name='Emoji Count'),
        ),
    ]
