# Generated by Django 3.2.16 on 2023-12-18 10:42

import community.bases.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0006_alter_community_options'),
        ('posts', '0004_auto_20231117_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Deleted')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='Deleted')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.IntegerField(default=1, verbose_name='Order')),
                ('post_data', models.JSONField(blank=True, null=True, verbose_name='Post Data')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='communities.community', verbose_name='Community')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='posts.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Community Post',
                'verbose_name_plural': 'Community Post',
                'ordering': ['order'],
            },
            bases=(community.bases.models.UpdateMixin, models.Model),
        ),
    ]
