from community.apps.community_medias.api.serializers.create import CommunityMediaCreateAdminSerializer
from community.apps.community_medias.api.serializers.retrieve import CommunityMediaRetrieveSerializer
