from community.apps.friends.api.serializers.create import FriendRequestCreateSerializer, FriendCreateSerializer
from community.apps.friends.api.serializers.index import FriendRequestSyncSerializer, FriendSyncSerializer
