# Generated by Django 3.2.16 on 2023-11-08 12:33

import community.bases.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Deleted')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='Deleted')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('write_permission', models.IntegerField(choices=[(0, 'GUEST'), (1, 'FARMER'), (2, 'KNIGHT'), (3, 'VISCOUNT'), (4, 'EARL'), (5, 'DUKE'), (6, 'KING'), (7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=1, verbose_name='포스트 작성 권한')),
                ('read_permission', models.IntegerField(choices=[(0, 'GUEST'), (1, 'FARMER'), (2, 'KNIGHT'), (3, 'VISCOUNT'), (4, 'EARL'), (5, 'DUKE'), (6, 'KING'), (7, 'STAFF'), (8, 'PRO_STAFF'), (9, 'SUPER_STAFF'), (10, 'MASTER')], default=0, verbose_name='포스트 조회 권한')),
                ('community_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='Community Title')),
                ('board_group_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='Board Group Title')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Description')),
                ('view_mode', models.CharField(choices=[('LIST_TYPE', 'LIST_TYPE'), ('ALBUM_TYPE', 'ALBUM_TYPE'), ('CARD_TYPE', 'CARD_TYPE')], default='LIST_TYPE', max_length=100, verbose_name='View Mode')),
                ('type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('ALL', 'ALL'), ('NOTICE', 'NOTICE'), ('EVENT', 'EVENT'), ('GALLERY', 'GALLERY'), ('VIDEO', 'VIDEO')], default='NORMAL', max_length=100, verbose_name='Type')),
                ('order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Board',
                'ordering': ['order'],
            },
            bases=(community.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BoardGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Deleted')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='Deleted')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('community_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='Community Title')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Order')),
                ('type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('DEFAULT', 'DEFAULT')], default='NORMAL', max_length=100, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Board Group',
                'verbose_name_plural': 'Board Group',
                'ordering': ['order'],
            },
            bases=(community.bases.models.UpdateMixin, models.Model),
        ),
    ]
