# Generated by Django 3.2.16 on 2023-11-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='Comment Count'),
        ),
        migrations.AddField(
            model_name='board',
            name='post_count',
            field=models.IntegerField(default=0, verbose_name='Post Count'),
        ),
    ]
