# Generated by Django 3.2.16 on 2024-04-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_insert_default_badge_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='image',
        ),
        migrations.AddField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='badge',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='badge',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='badge',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='badge',
            name='description_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='badge',
            name='description_ko',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='badge',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='badge',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='badge',
            name='description_zh_hant',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='badge',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='badge',
            name='short_title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Short Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='short_title_ar',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Short Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='short_title_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Short Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='short_title_es',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Short Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='short_title_ja',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Short Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='short_title_ko',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Short Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='short_title_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Short Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='short_title_zh_hans',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Short Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='short_title_zh_hant',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Short Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='title_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='title_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='title_ja',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='title_ko',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='title_zh_hans',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='badge',
            name='title_zh_hant',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
    ]
