# Generated by Django 3.2.16 on 2024-05-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_update_common_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(blank=True, choices=[('POST_ACTIVE', '포스트 활성화'), ('POST_PERIOD', '포스트 기간')], max_length=100, null=True, verbose_name='Badge Type'),
        ),
    ]
