# Generated by Django 3.2.16 on 2023-11-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='depth1_community_id',
            field=models.IntegerField(null=True, verbose_name='Depth1 Community ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='depth2_community_id',
            field=models.IntegerField(null=True, verbose_name='Depth2 Community ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='depth3_community_id',
            field=models.IntegerField(null=True, verbose_name='Depth3 Community ID'),
        ),
    ]
