# Generated by Django 3.2.16 on 2024-12-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20241219_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='emoji_count',
            field=models.IntegerField(default=0, verbose_name='Emoji Count'),
        ),
        migrations.AddField(
            model_name='post',
            name='emoji_point',
            field=models.IntegerField(default=0, verbose_name='Emoji Point'),
        ),
    ]
