# Generated by Django 3.2.16 on 2024-12-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20241219_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_emoji_count',
            field=models.IntegerField(default=0, verbose_name='Comments Emoji Count'),
        ),
    ]
