# Generated by Django 3.2.16 on 2023-12-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_medias', '0002_communitymedia_web_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityMedia',
        ),
    ]
